export const emoticons: Record<string, string[]> = {
	'Oo, Ow, Wow, Astonished': [
		':‑O',
		':O',
		':‑o',
		':o',
		':-0',
		':0',
		'8‑0',
		'>:O',
		'=O',
		'=o',
		'=0'
	],
	'Smiley, happy face': [
		':‑)',
		':)',
		':-]',
		':]',
		':->',
		':>',
		'8-)',
		'8)',
		':-}',
		':}',
		':o)',
		':c)',
		':^)',
		'=]',
		'=)'
	],
	'Laughing, big grin, grinning with glasses': [
		':‑D',
		':D',
		'8‑D',
		'8D',
		'=D',
		'=3',
		'B^D',
		'c:',
		'C:'
	],
	Laughing: ['x‑D', 'xD', 'X‑D', 'XD'],
	'Very happy or double chin': [':-))'],
	'Frown, sad, pouting': [
		':‑(',
		':(',
		':‑c',
		':c',
		':‑<',
		':<',
		':‑[',
		':[',
		':-||',
		':{',
		':@',
		':(',
		';('
	],
	Crying: [":'‑(", ":'(", ':=(', 'QQ', 'qq', 'Qq', '( ༎ຶ ۝ ༎ຶ )'],
	'Tears of happiness': [":'‑)", ":')", ':"D'],
	Angry: ['>:(', '>:['],
	'Horror, disgust, sadness, great dismay (right to left)': [
		"D‑':",
		'D:<',
		'D:',
		'D8',
		'D;',
		'D=',
		'DX'
	],
	'Cat face, curled mouth, cutesy, playful, mischievous': [':-3', ':3', '=3', 'x3', 'X3'],
	'Lion smile, evil cat': ['>:3'],
	Kiss: [':-*', ':*', ':×', '(๑ˇεˇ๑)'],
	'Wink, smirk': [';‑)', ';)', '*-)', '*)', ';‑]', ';]', ';^)', ';>', ':‑,', ';D', ';3'],
	'Tongue sticking out, cheeky/playful, blowing a raspberry': [
		':‑P',
		':P',
		'X‑P',
		'XP',
		'x‑p',
		'xp',
		':‑p',
		':p',
		':‑Þ',
		':Þ',
		':‑þ',
		':þ',
		':‑b',
		':b',
		'd:',
		'=p',
		'>:P'
	],
	'Skeptical, annoyed, undecided, uneasy, hesitant': [
		':-/',
		':/',
		':‑.',
		'>:\\',
		'>:/',
		':\\',
		'=/',
		'=\\',
		':L',
		'=L',
		':S',
		'>.<',
		'>_<'
	],
	'Straight face no expression, indecision': [':‑|', ':|'],
	'Embarrassed, blushing': [':$', '://)', '://3'],
	'Sealed lips, wearing braces, tongue-tied': [':‑X', ':X', ':‑#', ':#', ':‑&', ':&'],
	'Angel, halo, saint, innocent': ['O:‑)', 'O:)', '0:‑3', '0:3', '0:‑)', '0:)', '0;^)'],
	'Evil, devilish': ['>:‑)', '>:)', '}:‑)', '}:)', '3:‑)', '3:)', '>;‑)', '>;)', '>:3', ';3'],
	'Cool, bored, yawning': ['|;‑)', '|‑O', 'B-)'],
	'Tongue-in-cheek': [':‑J'],
	'Partied all night': ['#‑)'],
	'Drunk, confused': ['%‑)', '%)'],
	'Being sick': [':‑###..', ':###..'],
	'Dumb, dunce-like': ['<:‑|'],
	'Scepticism, disbelief, disapproval': ["',:-|", "',:-l"],
	'Grimacing, nervous, awkward': [':E'],
	'Skull and crossbones': ['8-X', '8=X', 'x-3', 'x=3'],
	Chicken: ['~:>'],
	Rose: ['@};-', '@}->--', "@}‑;‑'‑‑‑", '@>‑‑>‑‑'],
	'Penis, Ejaculation': ['8====D', '8===D', '8=D', '3=D', '8=>', '8===D~~~'],
	'Elvis Presley': ['5:‑)'],
	'Santa Claus': ['*<|:‑)'],
	'Homer Simpson': ['~(_8^(I)'],
	'Bill Clinton': ['=:o]'],
	'Ronald Reagan': ['7:^]', ',:‑)'],
	'Broken heart': ['</3', '<\\3'],
	Heart: ['<3'],
	"Fish, something's fishy, Christian fish": ['><>', '<><', '<*)))‑{', '><(((*>'],
	'Cheer, Yay, yay.': ['\\o/'],
	Cheerleader: ['*\\0/*'],
	Salute: ['o7'],
	'John Lennon': ['//0‑0\\\\'],
	Zoidberg: ['(V) (;,,;) (V)', '(V)(°,,°)(V)'],
	'Sadness, great dismay, disgust': ['v.v', '._.', '._.;'],
	'Dead person, fainted': ['X_X', 'x_x', '+_+', 'X_x', 'x_X'],
	'Sideways look. Devious or guilty.[irrelevant citation]': ['<_<', '>_>', '<.<', '>.>'],
	'Surprise, shock, yawn': ['O_O', 'o_o', 'O-O', 'o‑o', 'O_o', 'o_O'],
	'High five': ['^5', 'o/\\o', '>_>^ ^<_<'],
	'Crab, Lobster': ['V.v.V', 'V=(° °)=V'],
	Shark: ['(^^^)'],
	'Three TIE fighters': ['|-o-| [-o-] |-o-|'],
	Bandage: ['(::[]::)'],
	Breasts: ['(o)(o)', '( • )( • )'],
	'Darwin fish/Evolution fish': ['ӽd̲̅a̲̅r̲̅w̲̅i̲̅ɳ̲̅ᕗ', 'Ӽd̲̅a̲̅r̲̅w̲̅i̲̅ɳ̲̅ᕗ', 'ӽe̲̅v̲̅o̲̅l̲̅u̲̅t̲̅i̲̅o̲̅ɳ̲̅ᕗ', 'Ӽe̲̅v̲̅o̲̅l̲̅u̲̅t̲̅i̲̅o̲̅ɳ̲̅ᕗ'],
	'Dollar notes': ['[̲̅$̲̅(̲̅1̲̅)̲̅$̲̅]', '[̲̅$̲̅(̲̅5̲̅)̲̅$̲̅]', '[̲̅$̲̅(̲̅1̲̅0̲̅)̲̅$̲̅]', '[̲̅$̲̅(̲̅ιοο̲̅)̲̅$̲̅]'],
	'Lenny Face': ['( ͡° ͜ʖ ͡°)'],
	'Raise Your Dongers': ['ヽ༼ຈل͜ຈ༽ﾉ'],
	'Look of Disapproval': ['ಠ_ಠ', 'ಠ__ಠ', 'ಠ益ಠ'],
	Bat: ['⎛⎝(•ⱅ•)⎠⎞', '◥▅◤', '◢▅◣', '～°·_·°～'],
	'Flower Girl': ['(◕‿◕✿)'],
	Bear: ['ʕ •ᴥ•ʔ', 'ʕ ·(エ)· ʔ', 'ʕ – ㉨ – ʔ', '⊂(￣(ｴ)￣)⊃'],
	Troubled: ['(>_<)', '(>_<)>', '(>w<)'],
	Baby: ["(';')"],
	'Nervous, embarrassed, troubled, shy, sweat drop': [
		'(^^ゞ',
		'(^_^;)',
		'(-_-;)',
		'(~_~;)',
		'(・_・;)',
		'(・・;)',
		'^_^;',
		'(#^.^#)',
		'(^',
		'^;)'
	],
	'Embarrassed, flushed': ['(⁄ ⁄•⁄ω⁄•⁄ ⁄)'],
	Smoking: ['(^.^)y-.o○', '(-.-)y-°°°'],
	Sleeping: ['(-_-) zzz', '(︶｡︶✽)'],
	Wink: ['(^_-)', '(^_-)-☆'],
	Confused: ['((+_+))', '(+o+)', '(°°)', '(°-°)', '(°_°)', '(°_°>)', '(°レ°)'],
	Ultraman: ['(o|o)'],
	'—': ['(p_-)', '(-_q)'],
	Joyful: [
		'^_^',
		'(°o°)',
		'(^_^)/',
		'(^O^)／',
		'(^o^)／',
		'(^^)/',
		'(/◕ヮ◕)/',
		'(^o^)丿',
		'∩(·ω·)∩',
		'(·ω·)',
		'^ω^'
	],
	'Kowtow as a sign of respect, or dogeza for apology': [
		'(__)',
		'_(._.)_',
		'_(_^_)_',
		'<(_ _)>',
		'm(__)m',
		'm(_ _)m'
	],
	'Middle fingers': ['(凸ಠ益ಠ)凸'],
	Questioning: ['＼(°ロ＼)', '(／ロ°)／'],
	'Sad, crying': [
		"('_')",
		'(/_;)',
		'(T_T)',
		'(;_;',
		'(;_:)',
		'(;O;)',
		'(:_;)',
		'(ToT)',
		'(Ｔ▽Ｔ)',
		';-;',
		';n;',
		';;',
		'Q.Q',
		'T.T',
		'TnT',
		'QQ',
		'Q_Q'
	],
	Shame: ['(ー_ー)!!', '(-.-)', '(-_-)', '(一一)', '(；一_一)'],
	Tired: ['(=_=)'],
	Cat: ['(=^・^=)', '(=^・・^=)', '=^_^=', '(=ʘᆽʘ=)∫'],
	'Looking down in sadness or boredom': ['(..)', '(._.)'],
	'Giggling with hand covering mouth': ['^m^'],
	Confusion: ['(・・?', '(?_?)'],
	Facepalm: ['(－‸ლ)'],
	'Normal laugh': [
		'>^_^<',
		'<^!^>',
		'^/^',
		'（*^_^*）',
		'§^.^§',
		'(^<^)',
		'(^ム^)',
		'(^·^)',
		'(^.^)',
		'(^_^.)',
		'(^_^)',
		'(^^)',
		'(*^.^*)',
		'^_^',
		'(#^.^#)',
		'（^—^）'
	],
	Waving: [
		'(^^)/~~~',
		'(^_^)/~',
		'(;_;)/~~~',
		'(^.^)/~~~',
		'(-_-)/~~~',
		'(@^^)/~~~',
		'(T_T)/~~~',
		'(ToT)/~~~'
	],
	'Alien Baltan': ['(V)o￥o(V)'],
	Excited: ['＼(~o~)／', '＼(^o^)／', '＼(-o-)／', 'ヽ(^o^)丿', '(*^0^*)'],
	Amazed: ['(*_*)', '(*_*;', '(+_+)', '(@_@。', '(＠_＠;)', '＼(◎o◎)／！'],
	'Laughing, cheerful': [
		'(*^^)v',
		'(^^)v',
		'(^_^)v',
		'（’-’*)',
		'(＾▽＾)',
		'(・∀・)',
		'(´∀`)',
		'(⌒▽⌒）'
	],
	Hopeless: ['＼(^o^)／', '\\(^o^)/'],
	Calmness: ['ˊ＿>ˋ'],
	'Headphones, listening to music': ['((d[-_-]b))'],
	Worried: [
		'(-"-)',
		'(ーー゛)',
		'(^_^メ)',
		'(-_-メ)',
		'(~_~メ)',
		'(－－〆)',
		'(｀´)',
		'<`～´>',
		'<`ヘ´>',
		'(ーー;)'
	],
	Eyeglasses: ['(^0_0^)'],
	'Jotting note': ['( ..)φ', 'φ(..)'],
	Happy: [
		'(●＾o＾●)',
		'(＾ｖ＾)',
		'(＾ｕ＾)',
		'(＾◇＾)',
		'(^O^)',
		'(^o^)',
		'(^○^)',
		')^o^(',
		'(✿◠‿◠)'
	],
	Grinning: ['(￣ー￣)'],
	Surprised: ['(￣□￣;)', '°o°', '°O°', ':O', 'o_0', 'o.O', '(o.o)', 'oO'],
	Infatuation: ['(*´▽｀*)', '(*°∀°)=3'],
	'Dancing, swinging arms back and forth, Happy Gary': ['ᕕ( ᐛ )ᕗ'],
	'Shocked, surprised': ['（ ﾟ Дﾟ)', '(°◇°)'],
	Dissatisfied: ['(*￣m￣)'],
	'Mellow, shrug': ['ヽ(´ー｀)┌', '¯\\_(ツ)_/¯', '¯\\(°_o)/¯'],
	'Snubbed or deflated': ['(´･ω･`)', '(‘A`)'],
	'Hugging/reaching and kissing': ['(づ￣ ³￣)づ'],
	'Blowing a kiss': ['(*^3^)/~☆'],
	'Studying is good': ['.....φ(・∀・＊)'],
	'Joy or Cute': ['uwuUwU', 'UwU'],
	"what's this?": ['OWO', 'OwO'],
	'Distress. Jiong, a Chinese character meaning a patterned window': ['囧'],
	Bubbles: ['.o○○o.'],
	'Cup of tea': ['( ^^)_U~~( ^^)_旦~~'],
	'Shooting star': ['☆彡☆ミ'],
	Fish: ['>°)))彡(Q))><ヨヨ (°))<<>°))))彡<°)))彡>°))彡 <+))><<<*))>=<'],
	'Squid, octopus': ['<コ:彡 Ｃ:.ミ'],
	Snake: ['~>°)～～～'],
	Tadpole: ['(°°)～'],
	Bomb: ['●～*'],
	Despair: ['￣|○STOOTZOTLorz囧rz'],
	'Table flip': ['(╯°□°）╯︵ ┻━┻┬──┬ ¯\\_(ツ) ┻━┻︵ヽ(`Д´)ﾉ︵ ┻━┻┬─┬ノ( º _ ºノ) (ノಠ益ಠ)ノ彡┻━┻']
};
